#pywal color scheme
foreground   #82cde7
background   #0c1118
cursor       #82cde7

active_tab_foreground    #0c1118
active_tab_background    #82cde7
inactive_tab_foreground  #82cde7
inactive_tab_background  #0c1118

active_border_color     #82cde7
inactive_border_color   #0c1118
bell_border_color       #F15915

color0       #0c1118
color8       #5b8fa1
color1       #F15915
color9       #F15915
color2       #AB3D48
color10      #AB3D48
color3       #055FA0
color11      #055FA0
color4       #286BB8
color12      #286BB8
color5       #BB5EA3
color13      #BB5EA3
color6       #039BDF
color14      #039BDF
color7       #82cde7
color15      #82cde7

wayland_titlebar_color  background

background_opacity      .95

#fonts
bold_font         MesloLGS NF Bold
bold_italic_font  MesloLGS NF Bold Italic
font_family       MesloLGS NF Regular
italic_font       MesloLGS NF Italic
font_size         11.0

#misc
adjust_line_height      3
cursor_beam_thickness   10.0

#mouse
copy_on_select          yes

#window appearance
initial_window_height   545
initial_window_width    895
remember_window_size    no   
window_padding_width    10

#window resize
map ctrl+left resize_window narrower
map ctrl+right resize_window wider
map ctrl+up resize_window taller
map ctrl+down resize_window shorter 3
map ctrl+home resize_window reset

#window layouts
enabled_layouts Horizontal,Vertical,Tall,Fat,Grid 
