background {
    monitor =
    path = $HOME/Pictures/Wallpapers/tealpump.jpg 
    color = rgba(250, 179, 135, 1.0)

    blur_passes = 0
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 380, 52
    outline_thickness = 3
    dots_size = 0.23
    dots_spacing = 0.15
    dots_center = false
    dots_rounding = -1
    outer_color = rgba(250, 179, 135, 1.0)
    inner_color = rgba(69, 71, 90, 1.0)
    font_color = rgba(250, 179, 135, 1.0)
    fade_on_empty = false
    fade_timeout = 1000
    placeholder_text = <i>Input Password...</i>
    hide_input = false
    rounding = -1
    check_color = rgba(250, 179, 135, 1.0)
    fail_color = rgba(250, 179, 135, 1.0)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_timeout = 2000
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
  
    position = 0, 0
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] TZ=America/Chicago date "+%A, %B %e at %H:%M"
    text_align = center 
    color = rgba(69, 71, 90, 1.0)
    font_color = rgba(250, 179, 135, 1.0)
    font_size = 70
    font_family = Indie Flower
    rotate = 0

    position = 0, 175
    halign = center
    valign = center
}
