# Background
background {
    monitor =
    path = ~/Pictures/Wallpapers/beachhouse.jpg
    blur_passes = 2
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# Profie-photo
image {
    path = ~/Pictures/Icons/littlenerdsm.png
    size = 130
    border_size = 2
    border_color = rgba(255, 255, 255, 0)
    position = 0, 50
    halign = center
    valign = center
}

# Day-month-date
label {
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(189, 147, 249, 1.00)
    font_size = 25
    font_family = SF Pro Display Bold
    position = 0, 360
    halign = center
    valign = center
}

# Time
label {
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(255, 184, 108, 1.0)
    font_size = 110
    font_family = SF Pro Display Bold
    position = 0, 250
    halign = center
    valign = center
}

# Userbox
shape {
    size = 300, 50
    color = rgba(40, 42, 54, 1.0)
    rounding = -1
    border_color = rgba(253, 198, 135, 0)
    position = 0, -130
    halign = center
    valign = center
}

# User
label {
    text =    $USER
    color = rgba(189, 147, 249, 1.0)
    font_size = 18
    font_family = SF Pro Display Bold
    position = 0, -130
    halign = center
    valign = center
}

# Input field
input-field {
    size = 300, 50
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    inner_color = rgba(40, 42, 54, 1.0)
    font_color = rgba(189, 147, 249, 1.0)
    font_family = SF Pro Display Bold
    fade_on_empty = false
    placeholder_text = <span foreground="##bd93f9ff">🔒  Enter Password</span>
    hide_input = false
    check_color = rgba(40, 42, 54, 1.0)
    fail_color = rgba(40, 42, 54, 1.0)
    position = 0, -220
    halign = center
    valign = center
}
