"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$username\
[](bg:teal fg:surface0)\
$directory\
[](fg:teal bg:yellow)\
$git_branch\
$git_status\
[](fg:yellow bg:maroon)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:maroon bg:blue)\
$docker_context\
[](fg:blue bg:peach)\
$time\
[ ](fg:peach)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
base      = "#1f2335"
blue      = "#7aa2f7"
crust     = "#111111"
mantle    = "#24283b"
maroon    = "#ff757f"
peach     = "#ff9e64"
red       = "#c53b53"
surface0  = "#292e42"
teal      = "#7dcfff"
text      = "#c0caf5"
yellow    = "#ffc777"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Fedora = "󰣛"
Gentoo = "󰣨"
Linux = "󰌽"
Macos = ""
Manjaro = ""
Mint = "󰣭"
Raspbian = "󰐿"
RedHatEnterprise = "󱄛"
Redhat = "󱄛"
SUSE = ""
Ubuntu = "󰕈"
Windows = "󰍲"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:teal"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:maroon"
format = '[[ $symbol $branch ](fg:base bg:yellow)]($style)'

[git_status]
style = "bg:maroon"
format = '[[($all_status$ahead_behind )](fg:base bg:yellow)]($style)'

[nodejs]
symbol = ""
style = "bg:maroon"
format = '[[ $symbol( $version) ](fg:base bg:maroon)]($style)'

[c]
symbol = " "
style = "bg:maroon"
format = '[[ $symbol( $version) ](fg:base bg:maroon)]($style)'

[rust]
symbol = ""
style = "bg:maroon"
format = '[[ $symbol( $version) ](fg:base bg:maroon)]($style)'

[golang]
symbol = ""
style = "bg:maroon"
format = '[[ $symbol( $version) ](fg:base bg:maroon)]($style)'

[php]
symbol = ""
style = "bg:maroon"
format = '[[ $symbol( $version) ](fg:base bg:maroon)]($style)'

[java]
symbol = " "
style = "bg:maroon"
format = '[[ $symbol( $version) ](fg:base bg:maroon)]($style)'

[kotlin]
symbol = ""
style = "bg:maroon"
format = '[[ $symbol( $version) ](fg:base bg:maroon)]($style)'

[haskell]
symbol = ""
style = "bg:maroon"
format = '[[ $symbol( $version) ](fg:base bg:maroon)]($style)'

[python]
symbol = ""
style = "bg:maroon"
format = '[[ $symbol( $version) ](fg:base bg:maroon)]($style)'

[docker_context]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $context) ](fg:yellow bg:base)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:teal"
format = '[[  $time ](fg:mantle bg:peach)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ](bold fg:teal)'
error_symbol = '[ ](bold fg:red)'
vimcmd_symbol = '[](bold fg:teal)'
vimcmd_replace_one_symbol = '[](bold fg:blue)'
vimcmd_replace_symbol = '[](bold fg:blue'
vimcmd_visual_symbol = '[](bold fg:blue)'
